### ISSUE TITLE
deps: permission denied installing azure

### ISSUE THREAD

**Issue by tiago4orion** [NeowayLabs/klb#102]
```
git:(master)λ> make deps

...
npm ERR! Linux 4.7.0-rc7haswell-and-docker-friendly
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "--no-optional" "-g" "azure-cli"
npm ERR! node v7.6.0
npm ERR! npm  v4.3.0
npm ERR! path /usr/lib/node_modules/azure-cli/node_modules/ansi-regex
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/azure-cli/node_modules/ansi-regex'
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules/azure-cli/node_modules/ansi-regex'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules/azure-cli/node_modules/ansi-regex' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/i4k/.npm/_logs/2017-04-19T14_32_06_424Z-debug.log
make: *** [Makefile:20: azure-deps] Error 243
ERROR: <interactive>:1:0: exit status 2
```

changing the command to `sudo make deps` doesn't works because GOPATH isn't set in root environment.
Changing the Makefile rule "azure-deps" to use `sudo` works.

makes sense change that?

**Comment by katcipis** [comment]
@tiago4orion on the branch I'm working on I already created a hack/arch.sh that calls sudo. It is crap...I'm so desperate that I'm thinking about using the docker build stuff as the main way to run tests and stuff on the project. Managing this dependencies is just too fucking hard, and we all use the same distro...adding different distros will create hell to anyone who wants to dev and add some tests (the works for me stuff).

**Comment by katcipis** [comment]
@tiago4orion do we need to keep this open ?

**Comment by tiago4orion** [comment]
I think not. Closing.
