### ISSUE TITLE
testing: Vendor dependencies

### ISSUE THREAD

**Issue by katcipis** [NeowayLabs/klb#37]
Right now we just download the dependencies from master and pray to god it will work

**Comment by katcipis** [comment]
It is a little odd since klb itself does not depend on Go nash libraries, only the nash runtime installed. But it is bad to have no control at all of which version of nash is working and which is not. Not quite sure yet on how to solve this.

**Comment by katcipis** [comment]
For example, if the tests pass but on a different environment it is not working you could compare the vendored nash with the one used on the environment. Also it will make our tests more reproducible, right now it could happen that on one machine works and another one fails. To mitigate that we always go get -u on the dependencies...but I'm not sure this is a great idea, if something get broken on nash we are going to have problems running the tests.

**Comment by katcipis** [comment]
Right now the github API is down...I cant run the tests without the go get running :-) (of course you can comment it out from the Makefile if you installed the deps before). Just a curiosity

**Comment by tiago4orion** [comment]
Makes sense. Adding a vendored nash inside the tests directory should suffice. Right?

**Comment by katcipis** [comment]
@tiago4orion it would, but I started to get confused about differences on running on the host machine VS running the tests and how we could avoid this gap. For this we would have to provide the vendored nash cli/shell and an easy way for the user to run the examples/test scripts using this nash...that is the same as the one used on the tests.

**Comment by katcipis** [comment]
Or we could just vendor inside the tests and ignore the difference :-)
