### ISSUE TITLE
Missing aws instance iam instance profile

### ISSUE THREAD

**Issue by lborguetti** [NeowayLabs/klb#5]

**Comment by tiago4orion** [comment]
https://github.com/NeowayLabs/klb/blob/master/aws/iam.sh#L43 ?

**Comment by lborguetti** [comment]
Ok, but i can't create instance and set this role :(

**Comment by lborguetti** [comment]
Make sense?

**Comment by lborguetti** [comment]
No, no make sense!  We has this feature :+1:
