### ISSUE TITLE
Add check OS in jq installation (make deps)

### ISSUE THREAD

**Issue by mmsilveira** [NeowayLabs/klb#65]
JQ installation use binary file specific to operational system and it is hardcode jq-linux64.
For installation in Mac OS use jq-osx-amd64 file.

**Comment by lborguetti** [comment]
Nice @mmsilveira. Can you implement this verification ?

You need code like this:

```
OS := $(shell uname)
ifeq $(OS) Darwin
# Run MacOS commands 
else
# check for Linux and run other commands
endif
```

**Comment by katcipis** [comment]
We are converging to use containers to tame the dependencies monster =/, azure really does not go easy on this and managing manually azure cli 1.0 and 2.0 deps is really hard.

There are still some scripts to help those with strong hearts :-)
