### ISSUE TITLE
Add support for the new Azure CLI 2.0

### ISSUE THREAD

**Issue by vitorarins** [NeowayLabs/klb#85]
Azure has introduced a new CLI for its services here: https://github.com/Azure/azure-cli
Some people have already shown interest and some features will depend on it, like #45 
What do you guys think?

**Comment by katcipis** [comment]
I'm not planning on investing energy on this anytime soon if I'm not obligated (like the other cli support being completely dropped). The cost of migrating does not seem low, it has high risks, and at least for me it will not have a lot of benefit. But if someone is willing to, I would not oppose, as far as everything keeps working on a backwards compatible fashion :-)

**Comment by katcipis** [comment]
We added this because of the snapshot/managed disks feature. it is done ;-)
