### ISSUE TITLE
Fixing issues to create Managed Disks using CLI 2.0

### ISSUE THREAD

**Issue by fabioharams** [NeowayLabs/klb#96]
I found this article that demonstrating how to create a VM with Managed Disk using Azure CLi 2.0. Basically you need to create the Managed Disk first, create the VM and then attach the disk to VM. 

link: https://www.linkedin.com/pulse/azure-manage-disks-cli-20-asaf-nakash

**Comment by fabioharams** [comment]
By default when you a create a VM using CLi 2.0 the OS/Boot disk is automatically created as Managed Disk

**Comment by katcipis** [comment]
We got this working, thanks @fabioharams
